### ISSUE TITLE
403 error with addSourceLambdaPermission

### ISSUE THREAD

**Issue by pedrocaseiro** [dougmoscrop/serverless-plugin-log-subscription#21]
Using this plugin didn't seem to create the subscription I was expecting, so I've added a `addSourceLambdaPermission: true`. On deploy, started to get `An error occurred: MyFunctionLogLambdaPermission - Unable to parse HTTP response content (Service: AWSLambda; Status Code: 403; Error Code: null; Request ID: 64fd8522-1173-4d13-a8a3-72a2819c2566; Proxy: null).`

Any idea what I could be missing?

**Comment by rodrigogs** [comment]
It worked for me. The problem is that this options is not documented :/

**Comment by et304383** [comment]
The addSourceLambdaPermission needs to be documented and RENAMED.  It's a permission added to the **destination** function, not the source (which generated the logs) function.

**Comment by dougmoscrop** [comment]
addSourceLambdaPermission has been renamed to addLambdaPermission, it works simply now by detecting if the target looks like a lambda function.  The fact the status code is a 403 makes me wonder if you aren't allowed to add the permission to the function, but I can't know for sure.  If you're still facing this despite the fact it's bee six months please reopen with at least how you're declaring your subscription in your serverless.yml
