### ISSUE TITLE
Add API Gateway Log Group Subscription Filters

### ISSUE THREAD

**Issue by tedsmitt** [dougmoscrop/serverless-plugin-log-subscription#35]
Hi,

I've prepared a [branch](https://github.com/tedsmitt/serverless-plugin-log-subscription/tree/feature/apigw-log-subscriptions) which allows the configuration of subscription filters for the API Gateway access and execution log groups. Is this a feature you would be happy to add to this plugin?

Let me know your thoughts and I will submit a PR.

Cheers,
Ed

**Comment by tedsmitt** [comment]
Have opened https://github.com/dougmoscrop/serverless-plugin-log-subscription/pull/36 to start the discussion.

**Comment by dougmoscrop** [comment]
Published as 2.1.0!
