### ISSUE TITLE
Fresh Deployment Race Condition?

### ISSUE THREAD

**Issue by srg-avai** [dougmoscrop/serverless-plugin-log-subscription#4]
Deploying a fresh new stack with the serverless plugin was resulting in errors

```The specified log group does not exist..```

This error was preceded by the name of some log subscription, which seemed to differ each time I ran the deployment.  This kind of made me think of a race condition, so I removed all the log subscription plugin stuff from the yml, ran the deployment again and everything deployed fine.  Then I added back in the log subscription plugin and it deployed fine

Anyone experience this before?  I'm on latest - 1.1.0

thx

**Comment by dougmoscrop** [comment]
This makes sense in our case we're had services that are deployed, and then added this plugin. I don't add any `DependsOn` current. Will fix!

**Comment by dougmoscrop** [comment]
Should be fixed in 1.1.1 - can you try?

**Comment by srg-avai** [comment]
🥇 super quick turnaround @dougmoscrop  thanks so much!!
i just tested, all looks great w/ 1.1.1
