### ISSUE TITLE
Region missing error when deploying

### ISSUE THREAD

**Issue by coyoteecd** [dougmoscrop/serverless-plugin-log-subscription#44]
When log subscription for API Gateway logs is enabled (#36) - which apparently is the default! - my deployment fails with "Region is missing" error. 

I investigated a bit and the error comes from the isDeployed function [here](https://github.com/dougmoscrop/serverless-plugin-log-subscription/blob/07346bf3ecf5ab295a6a64e930ee94a73ee6848d/serverless-plugin-log-subscription.js#L286-L300).

That function is not implemented correctly, plugins should **not** instantiate their own AWS clients, instead use the `request` method provided by the Serverless Framework. See here an example in one my plugins: https://github.com/coyoteecd/serverless-s3-cleaner/blob/6c0b66c0652a5b186da252b6981f759d598b5f0a/src/index.ts#L134. Serverless Framework uses provider.region variable as target, and this may or may not be the same as the default region you have configured on your local PC. Indeed, a CI server may not even have it configured at all. The `request` method takes care of specifying the correct region in the SDK client, as well as other things.

**Comment by tedsmitt** [comment]
@coyoteecd Thanks for raising this, looking at implementing a fix now.

**Comment by madmaxrichter** [comment]
> @coyoteecd Thanks for raising this, looking at implementing a fix now.

@tedsmitt any update on this? We are having the same issue.

**Comment by tedsmitt** [comment]
@madmaxrichter I've just submitted a PR for this, had a fix sitting in a branch for a while. Have made some amendments today but you'll be able to test from [this branch](https://github.com/tedsmitt/serverless-plugin-log-subscription/tree/fix/%2344) if you wish to do so!
