### ISSUE TITLE
Seen this error before?

### ISSUE THREAD

**Issue by shawngrona** [dougmoscrop/serverless-plugin-log-subscription#6]
on deploy: ```<lambdaName>SubscriptionFilter: Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function```

I've been trying to figure out the problem, not making much headway, any help appreciated.

**Comment by shawngrona** [comment]
looks like the plugin is missing a perm like:
```
    const principal = `logs.${service.provider.region}.amazonaws.com`;
      LogForwardingLambdaPermission = {
        Type: 'AWS::Lambda::Permission',
        Properties: {
          FunctionName: arn,
          Action: 'lambda:InvokeFunction',
          Principal: principal,
        },
      }
```

**Comment by dougmoscrop** [comment]
Yeah it's expected that the user manages this at least that's what I err'd
on (open to making it smarter)

**Comment by rodrigogs** [comment]
What is the proper way to use this? I'm confused...

**Comment by dougmoscrop** [comment]
addSourceLambdaPermission was defaulted to false and will default to true for 2.0.0
