### ISSUE TITLE
What partition key is used when forwarding logs to kinesis?

### ISSUE THREAD

**Issue by rinnegan** [dougmoscrop/serverless-plugin-log-subscription#8]
Hi @dougmoscrop,
Partition key is important for scaling the kinesis stream.
It is not clear from reading the code what partition key is used when forwarding logs to kinesis stream? Can you please explain how this work?

**Comment by dougmoscrop** [comment]
This plugin doesn't ship anything, it just sets up the subscription, so if the destination is stream, that's some kind of AWS internal detail.

**Comment by dougmoscrop** [comment]
Also if you are going to use CloudWatch and you intend to do something like central logging, you can't really use these AWS solutions directly. You can subscribe CloudWatch to Firehose, you can subscribe Firehose to Elasticsearch, but you can't subscribe CloudWatch -> Firehose -> Elasticsearch.

It's ridiculous, I know, but that's how AWS implemented it.  CloudWatch sends multiple LogEvents per Record, and they're zipped.  Firehose does not understand this but you can fix that with a Transformation Lambda.  That Lambda, however, has to emit 1:1 input to output, which is hampered by the fact you actually get 1:N (N being LogEvents) from CloudWatch. The Elasticsearch indexer off of Firehose does not understand getting 'chunks' like this.

The options I am aware of are:

1. Firehose+Elasticsearch, but subscribe your CloudWatch Logs (using this plugin) to a Lambda function, and use something like https://github.com/dougmoscrop/lamberjack which will unpack the LogEvents and put them in firehose one-by-one

2. Lambda (with this plugin) to Elasticsearch, is simple of course, but that has some issues with concurrency and load, I started to work on something to this effect: https://www.npmjs.com/search?q=fauxerhose but decided it was not really worth it

3. Lambda (with this plugin) to Kinesis, and then an indexer off of Kinesis.

1) Downside is that there's a ~5 minute delay on your logs (imposed by Firehose) and it's relatively more expensive than Kinesis per-record-byte. Upside is its scales on use.

2) Is good for small systems (but Elasticsearch costs a lot anyway so..) but not so much larger ones

3) Has less latency, but you have to manage shards and scaling is crappy (scale up/down characteristics and limits, no autoscaling solution, especially from AWS, exists yet) and you pay for it even when it is not being used.

Uncharted territory is using fauxerhose to write to S3 and Athena to query, this can work depending on your size and use but beware minimum charges, and you don't get the same level of queryability as ES.

**Comment by rinnegan** [comment]
thanks @dougmoscrop. happy with the explanation
